### ISSUE TITLE
Support for OAuth V2 endpoints (and possibly other new ones)

### ISSUE THREAD

**Issue by Dam-Buty** [beginner-corp/slack#166]
Hi all !

I see that the [API.json](https://github.com/smallwins/slack/blob/master/src/api.json) file has not been generated in more than a year, and it is missing the new OAuth endpoint [`oauth.v2.access`](https://api.slack.com/methods/oauth.v2.access), and possibly others.

As a side-note, the script used to generate the api.json file seems to be based on HTML parsing of [this page](https://api.slack.com/methods). This mechanic could end up being broken by any random change in the HTML structure of the page. It has come to my attention that the whole Slack API is documented using the OpenAPI format [here](https://api.slack.com/specs/openapi/v2/slack_web.json) . Maybe this could be an improvement to the generate_-api-json script ?

**Comment by brianleroux** [comment]
indeed, when this client was created slack didn't have one nor did they have any OpenAPI docs. I'd be happy to accept a PR that updates this.

**Comment by Dam-Buty** [comment]
thanks for the answers ! i'll try and find some time to contribute ;)
